name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Dependencies
      working-directory: worksheet2/my-react-app
      run: npm install

    - name: Run Tests
      working-directory: worksheet2/my-react-app
      run: npm test -- --watchAll=false
