name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
<<<<<<< HEAD
=======

>>>>>>> 131b86b9 (Fix GitHub Actions path issue)
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
<<<<<<< HEAD
    - name: Install Dependencies
      run: |
        cd my-react-app && npm install
    - name: Run Tests
      run: |
        cd my-react-app && npm test -- --watchAll=false
=======

    -     - name: Install Dependencies
      run: npm ci
    - name: Run Tests
      run: npm test
